### ISSUE TITLE
uncertain bug of ibeo_core.cpp

### ISSUE THREAD

**Issue by zhipengak** [astuff/ibeo_core#14]
Here is the issue list:
1. The data type 0x2806 is not little endian format but big endian format.
In your source code: https://github.com/astuff/ibeo_core/blob/master/src/ibeo_core.cpp
The function "read_le" should be replace by "read_de".
![图片](https://user-images.githubusercontent.com/44044971/61924739-ae441580-af9b-11e9-9b5c-6821004c0bb5.png)

2. Check the line1623 in the same picture, there is no "cross acceleration" in this this 0x2806 message.
3. The offset number from  line1619 to line1624 is mistake.

Regarding to issue 2 and issue 3, you can check the ration from source code to the page 49 of ibeo document "9500028_Ibeo Interface Specification_Customer Documentation_v1.48.2.pdf" below, it can provide my points.
![图片](https://user-images.githubusercontent.com/44044971/61924768-d6337900-af9b-11e9-9a01-346bf0d4eb88.png)

**Comment by zhipengak** [comment]
Complement explanation of the issue 1:
The reason I think it is big endian is I also check the ibeo SDK from ibeo official.
![图片](https://user-images.githubusercontent.com/44044971/61925618-b1d99b80-af9f-11e9-99c3-b2108b899cb5.png)
They use function "readBE" in parse this massage.

**Comment by JWhitleyWork** [comment]
@zhipengak - I am sorry that it took us quite a while to get back to you. Could you possibly create a Pull Request to implement this change?

**Comment by zhipengak** [comment]
> @zhipengak - I am sorry that it took us quite a while to get back to you. Could you possibly create a Pull Request to implement this change?

But I saw there is no change of "read_le", it is still "read_be" like before.
Am I wrong about it?
